### ISSUE TITLE
Raise version of org.json:json (vulnerabilites), or move to gson

### ISSUE THREAD

**Issue by in-fke** [anotheria/configureme#22]
https://mvnrepository.com/artifact/net.anotheria/configureme/2.5.0
see
https://mvnrepository.com/artifact/org.json/json

OR: moskito-core depends on gson, so maybe move to the same framework so you are not using two different JSON frameworks?

**Comment by dvayanu** [comment]
Hello, this is actually an excellent point, thank you! We will look into it, but it should be easily adoptable.

**Comment by dvayanu** [comment]
2.5.1 fixes updates the library to circumvent the vulnerability. Update to GSON will be performed in a separate version.

**Comment by dvayanu** [comment]
https://github.com/anotheria/configureme/releases/tag/configureme-2.6.0 has no json dependencies anymore.
